services:
  network-deploy-service:
    networks:
      - erfanbank

  microservice-db-config:
    extends: network-deploy-service
    image: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      interval: 10s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD : root


  microservice-base-config:
    extends:
      network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environments:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configserver-config:
    extends:
      microservice-base-config
    depends_on:
      configserver:
        condition: service-healthy
    environments:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
