services:
  network-deploy-service:
    networks:
      - erfanbank

  microservice-base-config:
    extends:
      network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environments:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configserver-config:
    extends:
      microservice-base-config
    depends_on:
      configserver:
        condition: service-healthy
    environments:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  microservice-eureka-config:
    extends:
      microservice-configserver-config
    depends_on:
      eurekaserver:
        condition: service-healthy
      environments:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070:eureka