build:
  version: "1.0"

accounts:
  message: "this is a message form QA team"
  contactDetails:
    name: "Ali Akbari"
    email: "akbari@gmail.com"
  onCallSupport:
    - (2312 312312)
    - (21331 133213)