build:
  version: "1.0"

accounts:
  message: "this is a message form prod team"
  contactDetails:
    name: "Ali Karimi"
    email: "karimi@gmail.com"
  onCallSupport:
    - (021) 88-888
    - (021) 99-999